auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Zhongweibupt.github.io
url: http://zhongweibupt.github.io
feed: /atom.xml
author_info: <a href="http://blog.zhongweibupt.github.io/">Zhongweibupt.github.io</a>
